version: "3.3"
services:
    springapp:
        build: https://github.com/jordiesc/java-springboot-basic.git
        image: springapp
        ports: 
            - "8080:8080"
    apacheweb:
        build: .
        image: apacheweb 
        ports: 
            - "80:80"
            - "443:443"
              
